### ISSUE TITLE
Linedef action 160 (and possibly others) on control sector - highlighting of map sector lost if high byte field used

### ISSUE THREAD

**Issue by smeghammer** [ioan-chera/eureka-editor#86] opened 2021-09-23 20:09 UTC
## Eureka version 1.27b

Hi Printz, found a subtle bug for ya - 

When using tagged sectors and 3D floors, if sector IDs are between 1 and 255, on selecting the control sector line, the corresponding map sector is highlighted.

However, when I use the high byte field to extend sector IDs beyond 255, any **control sector line** that uses the high byte field **no longer highlights** the corresponding map sector when that control sector line is selected.

## For example:

If I set a map sector to have an ID of 257, and a corresponding 3D floor control sector line to be:

`1,1,0,255,1`

that is:

`TAG, TYPE, FLAGS, OPACITY, TAG_HI`

Where TAG + TAG_HI = 257, the 3D floor is generated correctly, as is the 3D floor in the 3D view in Eureka, BUT, the highlight of the map sector when the control sector line is selected no longer occurs.

smeghammer

**Comment by mistersector** [comment] 2021-09-24 05:30
This is caused by Eureka only assuming all actions follow the Doom format (tag, parameter, etc), instead of accounting for Zdoom actions that may have a different format. It's caused by any action that uses:

1) high byte field
2) any field other than the first to indicate the sector
3) uses lineID instead of tag 
4) uses thingID instead of tag
5) uses polyobject ID
In the case of (3) and (4) and (5), it highlights both the lineID / tID / polyobject when a sector has the same tag in the first field. If it uses any other field, Eureka does not highlight the associated sector / line / thing / polyobject.

eg
86:Polyobj_MoveToSpot (po, speed, target)
121:Line_SetIdentification (lineid, moreflags, reserved1, reserved2, lineid_hi)
180:Thing_SetTranslation (tid, translation)
181:Plane_Align (floor, ceiling, lineid)
183:Line_AlignCeiling (lineid, side)
184:Line_AlignFloor (lineid, side)
215:Teleport_Line (thisid, destid, flip)

**Comment by smeghammer** [comment] 2021-09-24 09:17
OK thanks for the info - I have certainly noticed that certain line specials where a first flag for something other than a sector ID is present will highlight any sectors that coincidentally have this same integer value as their sector ID. This is less of an issue because it is a highlight I can ignore. 

The main issue with the **non**-highlight referred to here is as a usability aid:  

It will likely make it difficult to map control sectors back to corresponding map sectors unless a manual note of map sector co-ordinates and corresponding control sector co-ordinates is kept... 

I guess it is a fairly major change to implement tracking of actions other than Doom format.

**Comment by mistersector** [comment] 2021-09-24 23:14
You're on the right track. Manual notes for are how I worked around this when mapping in zdoom format, even to the point of creating a template zdoom map to reuse default high byte control sectors / lineID/ etc , but its still something the editor should manage for you.

**Comment by ioan-chera** [comment] 2021-10-05 06:17
This is on hold until I fix the following:

- [ ] #95 (I can't test this if I get controlled crashes as I create a ZDoom-Hexen map)

**Comment by mistersector** [comment] 2021-10-06 00:38
BTW, #57 could be merged here as it describes the same problem,

**Comment by ioan-chera** [comment] 2021-10-08 20:40
Solved. Now highlighting is aware of the linedef special and what should be highlighted. The UGH files have been updated to clearly define the arg data types (tag, poly ID, TID, line ID). Documentation on UGH files is upcoming (#99). Let me know if you encounter any lines which fail to highlight tagged targets.

**Closed as completed by ioan-chera** 2021-10-08 20:40 UTC
